
#include <algorithm>
#include <vector>
#include <cstdlib>
#include <iostream>
#include <iterator>
#include <random>

#include "rng.h"
#include "utility.h"

using namespace std;

/// Entry point to the calc_average_plusplus program
/// \remark Must have at least 3 arguments. The first argument is the minimum
/// number generated by the random number generator, the second argument
/// is the maximum number generated by the random number generator, and
/// the third argument is how many elements to insert into the vector.
int main(int argc, char* argv[]) {
  if (argc < 4) {
    ErrorMessage(
        "Please provide two positive integers as the maximum and "
        "minimum for this exercise and the number of integers to "
        "generate.");
    exit(1);
  }
  string argv_one_minimum = string(argv[1]);
  string argv_two_maximum = string(argv[2]);
  string argv_three_number_elements = string(argv[3]);
  int minimum_number = 0;
  int maximum_number = 0;
  int number_elements = 0;
  try {
    minimum_number = stoi(argv_one_minimum);
  } catch (const exception& e) {
    ErrorMessage("Trouble converting the first argument to a number.");
    exit(1);
  }

  try {
    maximum_number = stoi(argv_two_maximum);
  } catch (const exception& e) {
    ErrorMessage("Trouble converting the second argument to a number.");
    exit(1);
  }

  try {
    number_elements = stoi(argv_three_number_elements);
  } catch (const exception& e) {
    ErrorMessage("Trouble converting the third argument to a number.");
    exit(1);
  }

  if (maximum_number <= minimum_number || maximum_number < 0 ||
      minimum_number < 0) {
    ErrorMessage(
        "Please make sure your first number is less than your second "
        "number and that they are both positive integers.");
    exit(1);
  }

  RandomNumberGenerator rng(minimum_number, maximum_number);
  vector<int> random_numbers(number_elements);
  
  FillVector(random_numbers, number_elements, rng);
  PrintVector(random_numbers);
  float average = CalculateAverage(random_numbers);
  cout << "The average value of the vector is " << average << "\n";
  int median = CalculateMedian(random_numbers);
  cout << "The median value of the vector is " << median << "\n";
  int mode = CalculateMode(random_numbers);
  cout << "The mode of the vector is " << mode << "\n";
  
  return 0;
}
